apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-new-applications
  # This is an extra long description
  description: The is my new application
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
